/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/7a6a05ca-34be-4cf8-b6fa-69785c34d37b 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float BPM;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
int sensor_pin = A0;
int pulse_signal = 0;
int upper_threshold = 860; //or your threshold of choice
int lower_threshold = 800; //or your threshold of choice
int counter = 0;

bool any_peak_detected = false;
bool first_peak_detected = false;
bool ignore = false;
unsigned long first_pulse_time = 0;
unsigned long second_pulse_time = 0;
unsigned long pulse_period = 0;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  delay(1500);
  initProperties();
  //Connect to cloud and get info/errors
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  //Wait for cloud connection
  while (ArduinoCloud.connected() != 1) {
    ArduinoCloud.update();
    delay(500);
    }
}

void loop() {
  ArduinoCloud.update();
  counter++;
  if (counter > 200){
    ArduinoCloud.update();
    Serial.println(BPM);
  counter = 0;
  }
    pulse_signal = analogRead(sensor_pin);
  //Serial.println(pulse_signal);
  delay(50);

  if (pulse_signal > upper_threshold && any_peak_detected == false) {
    any_peak_detected = true;
    
    if (first_peak_detected == false) {
      first_pulse_time = millis();
      first_peak_detected = true;
    } 
    else {
      second_pulse_time = millis();
      pulse_period = second_pulse_time - first_pulse_time;
      first_peak_detected = false;
    }
    // Do something about this peak
  }

  if (pulse_signal < lower_threshold) {
  any_peak_detected = false;
  }
  BPM = 60000/pulse_period;

  Serial.println(BPM);
  
  
}


